import { products, money } from './data.js';
import { getCart, addToCart, updateQuantity, cartCount } from './store.js';
import { getRoute, startRouter } from './router.js';

const app = document.querySelector('#app');
const cartBadge = document.querySelector('#cart-count');
const image = product => `<img src="${product.image}" srcset="${product.image}&w=480 480w, ${product.image}&w=900 900w" sizes="(max-width: 700px) 90vw, 30vw" width="900" height="1050" loading="lazy" decoding="async" alt="${product.name} in ${product.color}" />`;
const card = product => `<article class="product-card">${image(product)}<div><p class="product-meta">${product.category} · ${product.color}</p><h3>${product.name}</h3><p>${money(product.price)}</p><div class="card-actions"><a href="#/product/${product.id}">Details</a><button data-add="${product.id}">Add to bag</button></div></div></article>`;
const updateBadge = () => { cartBadge.textContent = cartCount(); };

function home() { return `<section class="hero"><div><p class="eyebrow">Designed for everyday</p><h1>Objects that make room for living.</h1><p class="lede">Thoughtfully selected essentials for a quieter, more useful home.</p><a class="button" href="#/shop">Explore the collection →</a></div><img src="https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=82" width="1200" height="900" fetchpriority="high" alt="Warm, calm living room" /></section><section class="feature"><p class="eyebrow">Latest arrivals</p><div class="product-grid">${products.slice(0, 3).map(card).join('')}</div></section>`; }
function shop() { return `<section class="page-head"><p class="eyebrow">The collection</p><h1>Good things, chosen well.</h1><div class="filters" role="group" aria-label="Product category"><button class="is-active" data-category="All">All</button>${[...new Set(products.map(p => p.category))].map(category => `<button data-category="${category}">${category}</button>`).join('')}</div></section><section id="catalog" class="product-grid">${products.map(card).join('')}</section>`; }
function product(id) { const item = products.find(p => p.id === id); if (!item) return notFound(); return `<section class="product-detail">${image(item)}<div><a class="back" href="#/shop">← Back to shop</a><p class="eyebrow">${item.category} · ${item.color}</p><h1>${item.name}</h1><p class="price">${money(item.price)}</p><p class="lede">A practical, beautiful essential designed to hold up to daily use and age with character.</p><button class="button" data-add="${item.id}">Add to bag</button></div></section>`; }
function cart() { const items = getCart().map(entry => ({ ...products.find(product => product.id === entry.id), quantity: entry.quantity })).filter(item => item.id); if (!items.length) return `<section class="empty"><p class="eyebrow">Your bag</p><h1>Your bag is waiting.</h1><p class="lede">Find something useful for the days ahead.</p><a class="button" href="#/shop">Browse products →</a></section>`; const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0); return `<section class="cart"><div><p class="eyebrow">Your bag</p><h1>Selected essentials.</h1>${items.map(item => `<article class="cart-item">${image(item)}<div><h2>${item.name}</h2><p>${money(item.price)}</p><div class="quantity"><button aria-label="Decrease ${item.name}" data-quantity="${item.id}" data-amount="-1">−</button><span>${item.quantity}</span><button aria-label="Increase ${item.name}" data-quantity="${item.id}" data-amount="1">+</button></div></div><strong>${money(item.price * item.quantity)}</strong></article>`).join('')}</div><aside><p>Subtotal <strong>${money(total)}</strong></p><small>Taxes and shipping are calculated at checkout.</small><button class="button" data-checkout>Demo checkout →</button></aside></section>`; }
function about() { return `<section class="empty"><p class="eyebrow">Our story</p><h1>Less, but better.</h1><p class="lede">Luma Supply is a fictional catalogue built to demonstrate modular JavaScript, client-side routing, responsive images, and persistent cart state.</p><a class="button" href="#/shop">Shop the collection →</a></section>`; }
function notFound() { return `<section class="empty"><p class="eyebrow">404</p><h1>That page wandered off.</h1><a class="button" href="#/">Return home →</a></section>`; }
function render() { const { page, id } = getRoute(); app.innerHTML = ({ home: home(), shop: shop(), product: product(id), cart: cart(), about: about() }[page] || notFound()); updateBadge(); app.focus(); }

document.addEventListener('click', event => { const add = event.target.closest('[data-add]'); const quantity = event.target.closest('[data-quantity]'); if (add) { addToCart(add.dataset.add); updateBadge(); add.textContent = 'Added ✓'; setTimeout(() => { add.textContent = 'Add to bag'; }, 900); } if (quantity) { updateQuantity(quantity.dataset.quantity, Number(quantity.dataset.amount)); render(); } if (event.target.closest('[data-checkout]')) alert('Demo checkout complete. No payment was processed.'); });
document.addEventListener('click', event => { const category = event.target.closest('[data-category]'); if (!category) return; document.querySelectorAll('[data-category]').forEach(button => button.classList.toggle('is-active', button === category)); const selected = category.dataset.category; document.querySelector('#catalog').innerHTML = products.filter(product => selected === 'All' || product.category === selected).map(card).join(''); });
startRouter(render);
